/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store.management.system;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Juan
 */
public class Dashboard extends javax.swing.JFrame {
   
    /**
     * Creates new form Dashboard
     */
    public Dashboard() throws SQLException {
        initComponents();
        panelStarter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SalesByDayPanel = new javax.swing.JPanel();
        LowStockPanel = new javax.swing.JPanel();
        SalesByMonthPanel = new javax.swing.JPanel();
        SalesByWeekPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 250));

        jButton2.setText("Back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButton2)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 3, 3));

        javax.swing.GroupLayout SalesByDayPanelLayout = new javax.swing.GroupLayout(SalesByDayPanel);
        SalesByDayPanel.setLayout(SalesByDayPanelLayout);
        SalesByDayPanelLayout.setHorizontalGroup(
            SalesByDayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        SalesByDayPanelLayout.setVerticalGroup(
            SalesByDayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel3.add(SalesByDayPanel);

        javax.swing.GroupLayout LowStockPanelLayout = new javax.swing.GroupLayout(LowStockPanel);
        LowStockPanel.setLayout(LowStockPanelLayout);
        LowStockPanelLayout.setHorizontalGroup(
            LowStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        LowStockPanelLayout.setVerticalGroup(
            LowStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel3.add(LowStockPanel);

        javax.swing.GroupLayout SalesByMonthPanelLayout = new javax.swing.GroupLayout(SalesByMonthPanel);
        SalesByMonthPanel.setLayout(SalesByMonthPanelLayout);
        SalesByMonthPanelLayout.setHorizontalGroup(
            SalesByMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        SalesByMonthPanelLayout.setVerticalGroup(
            SalesByMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel3.add(SalesByMonthPanel);

        javax.swing.GroupLayout SalesByWeekPanelLayout = new javax.swing.GroupLayout(SalesByWeekPanel);
        SalesByWeekPanel.setLayout(SalesByWeekPanelLayout);
        SalesByWeekPanelLayout.setHorizontalGroup(
            SalesByWeekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        SalesByWeekPanelLayout.setVerticalGroup(
            SalesByWeekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel3.add(SalesByWeekPanel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void panelStarter(){
        String query = "SELECT monthname(invoiceDate), sum(totalPrice) FROM store_management_system.purchaseinvoices GROUP BY monthname(invoiceDate);";
        try { 
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(new DatabaseManipulator().ConnectDB(), query);
            JFreeChart chart = ChartFactory.createLineChart("Sales By Month", "Month", "Total sale", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(400, 450));
            chartPanel.setVisible(true);
            SalesByDayPanel.setLayout(new BorderLayout());
            SalesByDayPanel.add(chartPanel, BorderLayout.CENTER);
            SalesByDayPanel.validate();
            SalesByDayPanel.setVisible(true);      
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        query = "SELECT name, quantity FROM stockitems WHERE quantity < 50;";
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(new DatabaseManipulator().ConnectDB(), query);
            JFreeChart chart = ChartFactory.createBarChart("Low stock chart", "Item Name", "Stock level", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartPanel panel = new ChartPanel(chart);
            panel.setPreferredSize(new Dimension(400, 450));
            panel.setVisible(true);
            LowStockPanel.setLayout(new BorderLayout());
            LowStockPanel.add(panel, BorderLayout.CENTER);
            LowStockPanel.validate();
            LowStockPanel.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "SELECT invoiceDate, sum(totalPrice) FROM purchaseinvoices group by invoiceDate;";
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(new DatabaseManipulator().ConnectDB(), query);
            JFreeChart chart = ChartFactory.createLineChart("Sales By Day", "Date", "Total sale", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartPanel panel = new ChartPanel(chart);
            panel.setPreferredSize(new Dimension(400, 450));
            panel.setVisible(true);
            SalesByMonthPanel.setLayout(new BorderLayout());
            SalesByMonthPanel.add(panel, BorderLayout.CENTER);
            SalesByMonthPanel.validate();
            SalesByMonthPanel.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "SELECT DATE_FORMAT(invoiceDate, '%b %e') AS Week, totalPrice FROM purchaseinvoices group by Week;";
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(new DatabaseManipulator().ConnectDB(), query);
            JFreeChart chart = ChartFactory.createLineChart("Sales By Week", "Week", "Sales", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartPanel panel = new ChartPanel(chart);
            panel.setPreferredSize(new Dimension(400, 450));
            panel.setVisible(true);
            SalesByWeekPanel.setLayout(new BorderLayout());
            SalesByWeekPanel.add(panel, BorderLayout.CENTER);
            SalesByWeekPanel.validate();
            SalesByWeekPanel.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LowStockPanel;
    private javax.swing.JPanel SalesByDayPanel;
    private javax.swing.JPanel SalesByMonthPanel;
    private javax.swing.JPanel SalesByWeekPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
